name: Supercharacter_theory
version: "0.1"
license: "GPL-2.0-or-later"
date: 2022-02-24
description: |
    SUT

authors:
    - name: Fatemeh Moftakhar
      url: mailto:f.k.moftakhar@gmail.com

maintainers:
    - name: Fatemeh Moftakhar
      url: mailto:f.k.moftakhar@gmail.com

GAP: ">= 4.11"

www: https://fkmoftakhar.github.io/SUT/
readme: README.md
packageinfo: https://fkmoftakhar.github.io/SUT/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/fkmoftakhar/SUT/releases/download/v0.1/Supercharacter_theory-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Mof22</span>]   <b class='BibAuthor'>Moftakhar, F.</b>,
     <i class='BibTitle'>Supercharacter_theory, SUT,
             Version 0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://fkmoftakhar.github.io/SUT/">https://fkmoftakhar.github.io/SUT/</a></span>.
    </p>
    

bibtex: |
    @misc{ Supercharacter_theory0.1,
      author =           {Moftakhar, F.},
      title =            {{Supercharacter{\textunderscore}theory}, SUT, {V}ersion 0.1},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href   {https://fkmoftakhar.github.io/SUT/}  {\texttt{https://fkmoftakhar.github.io/}\discretionary
                          {}{}{}\texttt{SUT/}}},
      printedkey =       {Mof22}
    }

